#pragma once

/* %CFG_VERSION_MAJOR% */
#define _BACKYARD_ENGINE_VERSION_MAJOR 0

/* %CFG_VERSION_MINOR% */
#define _BACKYARD_ENGINE_VERSION_MINOR 0

/* %CFG_VERSION_PATCH% */
#define _BACKYARD_ENGINE_VERSION_PATCH 1

/* %CFG_VERSION_SUFFIX% */
#define _BACKYARD_ENGINE_VERSION_SUFFIX "alpha"

/* %CFG_VERSION_BRANCH% */
#define _BACKYARD_ENGINE_VERSION_BRANCH "dev"

/* %CFG_VERSION_FULL% */
#define _BACKYARD_ENGINE_VERSION "0.0.1-alpha(dev)"
